name: Sync to Personal GitHub

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove GitHub Actions Workflow Before Pushing
        run: |
          git config --global user.email "mihir.khatwani@gmail.com"
          git config --global user.name "mihirk"
          
          git remote add personal https://mihirk:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/mihirk/goodpay-website.git

          git checkout -b temp-sync  
          rm -rf .github/workflows/sync-to-personal.yml  # Remove GitHub Actions before syncing
          git commit -am "Remove GitHub Actions before syncing"

          git push --force personal temp-sync:main

    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}