name: Mirror to Personal Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "mihirk"
          git config --global user.email "mihir.khatwani@gmail.com"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Remove workflow file
        run: |
          rm .github/workflows/sync-to-personal.yaml
          git add .github/workflows/sync-to-personal.yaml

      - name: Mirror to personal repository
        run: |
          git remote add personal "git@github.com:mihirk/goodpay-website.git"
          git checkou
          git push -f personal "${{ github.ref }}"